"""security hardening and audit metadata

Revision ID: 871d7c4ab3f9
Revises: 83681c65734f
Create Date: 2026-09-10 10:27:33.051845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '871d7c4ab3f9'
down_revision = '83681c65734f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('request_method', sa.String(length=12), nullable=True))
        batch_op.add_column(sa.Column('request_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('request_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('user_agent', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_request_id'), ['request_id'], unique=False)

    with op.batch_alter_table('user_access', schema=None) as batch_op:
        batch_op.create_index('uq_active_cooperative_executive_position', ['cooperative_id', 'role'], unique=True, sqlite_where=sa.text("status = 'Active' AND cooperative_id IS NOT NULL"), postgresql_where=sa.text("status = 'Active' AND cooperative_id IS NOT NULL"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_access', schema=None) as batch_op:
        batch_op.drop_index('uq_active_cooperative_executive_position', sqlite_where=sa.text("status = 'Active' AND cooperative_id IS NOT NULL"), postgresql_where=sa.text("status = 'Active' AND cooperative_id IS NOT NULL"))

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_request_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))
        batch_op.drop_column('user_agent')
        batch_op.drop_column('request_id')
        batch_op.drop_column('request_path')
        batch_op.drop_column('request_method')
        batch_op.drop_column('ip_address')

    # ### end Alembic commands ###
